/**
 * Supabase Edge Function: taskweft-edge
 *
 * Loads the Popcorn-generated AtomVM bundle and routes HTTP requests into
 * the Elixir Taskweft.Edge process.
 *
 * ## Build steps (one-time per change)
 *
 *   # 1. Switch to the Popcorn toolchain (OTP 26.0.2 + Elixir 1.17.3)
 *   mise install   # reads .mise.toml
 *
 *   # 2. Build the AtomVM WASM runtime (first time only, ~10 min)
 *   mix popcorn.build_runtime
 *
 *   # 3. Compile the Elixir project into bundle.avm + atomvm.wasm
 *   mix popcorn.cook --include-vm
 *
 *   # 4. Deploy
 *   supabase functions deploy taskweft-edge
 *
 * ## supabase/config.toml — static_files entry
 *
 *   [functions.taskweft-edge]
 *   static_files = [
 *     "./functions/taskweft-edge/bundle.avm",
 *     "./functions/taskweft-edge/atomvm.wasm",
 *     "./functions/taskweft-edge/atomvm.js",
 *   ]
 *
 * ## Known constraints
 *
 *   1. Popcorn's WASM runtime uses SharedArrayBuffer which requires
 *      Cross-Origin-Opener-Policy: same-origin and
 *      Cross-Origin-Embedder-Policy: require-corp headers.
 *      Supabase Edge Functions do not inject these automatically; a
 *      response wrapper (see below) must set them.
 *
 *   2. atomvm.js targets browsers; Deno-specific globals (Deno.serve,
 *      import.meta.url) must be shimmed or the file adapted.
 *
 *   3. AtomVM does not support Erlang NIFs — confirmed non-issue here
 *      because all NIF calls go through the pure Elixir fallbacks in
 *      lib/taskweft/.
 */

// @ts-ignore — atomvm.js generated by `mix popcorn.cook --include-vm`
import { AtomVM } from "./atomvm.js";

const avmResponse = await fetch(new URL("./bundle.avm", import.meta.url));
const avmBytes = new Uint8Array(await avmResponse.arrayBuffer());

const vm = await AtomVM.init({
  wasmPath: new URL("./atomvm.wasm", import.meta.url).pathname,
});

vm.load(avmBytes);

const edgePid = vm.spawn("Elixir.Taskweft.Edge", "main", []);

Deno.serve(async (req: Request) => {
  const body = await req.json().catch(() => ({}));

  const result = await new Promise<Record<string, unknown>>((resolve) => {
    const self = vm.self();
    vm.send(edgePid, { request: self, body });
    vm.receive(self, ({ response }: { response: Record<string, unknown> }) =>
      resolve(response)
    );
  });

  return new Response(JSON.stringify(result), {
    headers: {
      "Content-Type": "application/json",
      // Required for AtomVM SharedArrayBuffer in Deno.
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Embedder-Policy": "require-corp",
    },
  });
});
